/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hp' at '16-10-14 上午8:55' with Gradle 2.13
 *
 * @author hp, @date 16-10-14 上午8:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
