server:
  port: 8080
  ssl:
    enabled: false
    protocol: TLS
    key-store: classpath:bmbserverca.keystore
    key-store-password: 880716
    trust-store: classpath:bmbserverca.keystore
    trust-store-password: 880716
rides:
  enabled: false
spring:
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password: 
#    max-active: 8
#    pool:
#      max-wait: -1  
#      max-idle: 8  
#      min-idle: 0  
#    timeout: 0 
#    expireEnabled: false
#    expireTime: 15
#    expireUnit: SECONDS
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: file:d:/release/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#  datasource:
#    url: jdbc:mysql://localhost:3306/ysx?serverTimezone=UTC
#    username: root
#    password: root
#    driverClassName: com.mysql.jdbc.Driver
#  jpa:
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update  
#      dialect: org.hibernate.dialect.MySQL5Dialect 
  datasource: 
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_test
    username: postgres
    password: 111111
  jpa:
    database_platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show_sql: true
    hibernate: 
      ddl_auto: update
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
  freemarker:
    suffix: .html
    exposeRequestAttributes: true
    exposeSpringMacroHelpers: true
    requestContextAttribute: requestContext
    settings:
      number_format: "0.##"
      template_update_delay: 5
      classic_compatible: true
      auto_import: 